### ISSUE TITLE
Activity to add a new plane. 

### ISSUE THREAD

**Issue by ishansaksena** [leedsjb/aviation-preflight-manager#11]
Select from a list and add details in activity with a form.

**Comment by leedsjb** [comment]
The way I was thinking this might work is to query the ICAO aircraft models API. Then when you choose a model from the list it is added to your user profile in Firebase as one of your planes. API details are here:

https://www.icao.int/safety/iStars/Pages/API-Data-Service.aspx

**Comment by ishansaksena** [comment]
We have the activity to select planes from, we need to make it write to firebase, and show it in the activity.
