### ISSUE TITLE
NavDrawer info

### ISSUE THREAD

**Issue by ishansaksena** [leedsjb/aviation-preflight-manager#15]
Add header in navdrawer to show user pic, user name etc. like in mockups

**Comment by leedsjb** [comment]
@jlibman Please refactor class to be named NavDrawer instead of navDrawer. 
EDIT: Nevermind, @ishansaksena told me this class is deprecated.

**Comment by ishansaksena** [comment]
Deleted the navdrawer class and unnecessary XML
